### ISSUE TITLE
私聊充值时，card.py文件101行报错

### ISSUE THREAD

**Issue by Jikexiaobai** [pcrbot/authMS#27]
全部报错内容为：
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nonebot/command/__init__.py", line 881, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/usr/local/lib/python3.9/site-packages/nonebot/command/__init__.py", line 173, in run
    await self.func(session)
  File "/HoshinoBot/hoshino/modules/authMS/card.py", line 101, in reg_group_chat
    group_name = await util.get_group_name(sid, gid)
AttributeError: module 'hoshino.modules.authMS.util' has no attribute 'get_group_name'
[2021-07-22 23:02:44,256 nonebot] DEBUG: Session of command ('充值',) finished

请问如何解决

**Comment by 3273576540** [comment]
> 全部报错内容为： Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/nonebot/command/**init**.py", line 881, in _real_run_command await asyncio.wait_for(future, timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 442, in wait_for return await fut File "/usr/local/lib/python3.9/site-packages/nonebot/command/**init**.py", line 173, in run await self.func(session) File "/HoshinoBot/hoshino/modules/authMS/card.py", line 101, in reg_group_chat group_name = await util.get_group_name(sid, gid) AttributeError: module 'hoshino.modules.authMS.util' has no attribute 'get_group_name' [2021-07-22 23:02:44,256 nonebot] DEBUG: Session of command ('充值',) finished
> 
> 请问如何解决

想问下你解决了这个问题嘛，util文件里好像没有这块

**Comment by 3273576540** [comment]
ok修好了
